openapi: 3.0.0
info:
  title: HelloService
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Retrieve an example resource
      responses:
        '200':
          description: Successful response